config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  devise_for :users
  resources :questions do
    resources :comments, only: [:create, :destroy]
    resources :answers
    resource :vote, only: [:create, :destroy]
  end
  resources :answers do
    resources :comments, only: [:create, :destroy]
    resource :vote, only: [:create, :destroy]
  end

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  validates_presence_of :title, :description
  validates_length_of :title, :description, minimum: 10

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all.order('created_at DESC')
    if params[:search].present?
      @questions = @questions.where("lower(title) LIKE ? OR lower(description) LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question), notice: "Question was successfully created"
    else
      render 'new'
    end
  end

  def show
    # Se inicializan para evitar errores por NilClass en los if que buscan errores
    @answer = Answer.new
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to root_path, notice: "Question was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path, notice: "Question was successfully deleted"
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :description)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_commentF.html.erb
<% if user_signed_in? %>
  <%= form_for [@question, @question.comments.build] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class:"form-control", placeholder: "Ingresa tu comentario" %>
    </div>
    <div class="form-group">
      <%= f.submit "Comentar", class:"btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/questions/_comments_form.html.erb
<% if user_signed_in? %>
  <%= form_for [commentable, commentable.comments.new] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class:"form-control", placeholder: "Ingresa tu comentario" %>
    </div>
    <div class="form-group">
      <%= f.submit "Comentar", class:"btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', obj: @question %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Publicar Pregunta</h1>
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class:"form-control", placeholder: "Titulo" %>
      </div>
      <div class="form-group">
        <%= f.text_area :description, class:"form-control", placeholder: "Descripción", rows:10 %>
      </div>
      <div class="form-group">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/_votes.html.erb
<!-- Se hace una condición ternaria comparando la clase del LOCALE que se pasa al render, si es tipo ANSWER pasa la ruta a voto de respuesta si no al de pregunta -->

<% if votable.voted_by?(current_user) %>
  <%= link_to (votable.class == Answer ? answer_vote_path(votable) : question_vote_path(votable)), method: :delete, class: "item-upvote upvote-active" do %>
    <span class="upvote-arrow"></span>
    <span class="upvote-count"><%= votable.votes.count %></span>
  <% end %>
<% else %>
  <%= link_to (votable.class == Answer ? answer_vote_path(votable) : question_vote_path(votable)), method: :post, class: "item-upvote" do %>
    <span class="upvote-arrow"></span>
    <span class="upvote-count"><%= votable.votes.count %></span>
  <% end %>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Preguntas</h1>
<div class="text-right">
  <%= link_to "Hacer una Pregunta", new_question_path, class:"btn btn-primary" %>
  <br><br>
</div>
  <div class="row">
    <table class="table table-stripped">
      <% @questions.each do |question| %>
        <tr>
          <td class="v-r">
            <%= question.votes.count %>
            <p class="creator">Votos</p>
          </td>
          <td class="v-r">
            <%= question.answers.count %>
            <p class="creator">Respuestas</p>
          </td>
          <td class="espaciado">
            <%= link_to question.title, question, class:"title" %> <br>
            <p class="creator">Preguntó <%= question.user.email %> hace <%= time_ago_in_words(question.created_at) %></p>
          </td>
        </tr>
      <% end %>
    </table>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<% if @answer.errors.any? %>
  <%= render 'layouts/errors', obj: @answer %>
<% end %>
<% if @comment.errors.any? %>
  <%= render 'layouts/errors', obj: @comment %>
<% end %>

<h2><%= @question.title %></h2>
<br>
<div class="row">
  <div class="col-sm-1 vote">
    <!-- Poner los votos -->
    <%= render 'questions/votes', votable: @question %>
  </div>
  <div class="col-sm-11">
    <p><%= markdown(@question.description) %></p>
    <br>
    <% @question.comments.each do |comment| %>

      <!-- ****** CON PANELES ****** -->
      <!-- <div class="panel panel-default">
        <header class="panel-heading">
          <strong><%= comment.user.email %> commented this <%= time_ago_in_words(comment.created_at) %> ago</strong>
        </header>
        <div class="panel-body">
          <%= comment.body %>
        </div>
        <% if comment.user == current_user %>
          <div class="panel-footer">
            <%= link_to "Delete", question_comment_path(@question, comment), method: :delete, class:"btn btn-danger btn-sm" %>
          </div>
        <% end %>
      </div> -->
      <!-- ****** CON PANELES FIN ****** -->

      <!-- ****** COMO TEXTO ****** -->
      <p class="comment"><%= comment.body %> — <span class="creator"><%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</span></p>
      <% if comment.user == current_user %>
        <div class="text-right">
          <%= link_to "Delete", question_comment_path(@question, comment), method: :delete, class:"btn btn-danger btn-sm" %>
          <br><br>
        </div>
      <% end %>
    <% end %>

    <%= render 'questions/comments_form', commentable: @question %>
    <!-- ****** COMO TEXTO FIN ****** -->
  </div>
</div>

<h3><%= pluralize(@question.answers.count, "answer") %></h3>
<br>
<% @question.answers.each do |answer| %>
  <div class="row">
    <div class="col-sm-1">
      <!-- Poner los votos -->

      <%= render 'questions/votes', votable: answer %>

    </div>
    <div class="col-sm-11">
        <p><%= markdown(answer.body) %></p>
        <p class="text-right creator">Answered by <%= answer.user.email %> <%= time_ago_in_words(answer.created_at) %> ago</p>
        <% if answer.user == current_user %>
          <%= link_to "Delete", question_answer_path(@question, answer), method: :delete, class:"btn btn-danger btn-sm" %>
          <br>
        <% end %>
        <br>

        <!-- Mostrar Comentarios de las respuestas -->
        <% answer.comments.each do |comment| %>
          <p class="comment"><%= comment.body %> — <span class="creator"><%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</span></p>
          <% if comment.user == current_user %>
            <div class="text-right">
              <%= link_to "Delete", answer_comment_path(answer, comment), method: :delete, class:"btn btn-danger btn-sm" %>
              <br><br>
            </div>
          <% end %>
        <% end %>

        <!-- Mostrar formulario para hacer un comentario a respuestas -->
        <%= render 'questions/comments_form', commentable: answer %>
        <br>
    </div>
  </div>
<% end %>

<!-- Escribir respuestas -->
<h4>Tu respuesta</h4>
<hr>

<% if user_signed_in? %>
  <%= form_for [@question, @question.answers.build] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class:"form-control", rows: 10 %>
    </div>
    <div class="form-group">
      <%= f.submit class:"btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <pre>Debes estar logueado para poder generar una respuesta</pre>
<% end %>