config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  devise_for :users
  resources :questions do
    resources :comments, only: [:create, :destroy]
    resources :answers
    resource :vote, only: [:create, :destroy]
  end
  resources :answers do
    resources :comments, only: [:create, :destroy]
    resource :vote, only: [:create, :destroy]
  end

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <a href="#" class="close" data-dismiss="alert" style="margin-right: 10px">&#215;</a>
        <div class="panel-heading">
          <h2 class="panel-heading">
            <%= pluralize(obj.errors.count, "error") %>
            phobited this <%= obj.class.to_s.downcase %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-inverse navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "ProyectoStackoverflow", root_path, class:"navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li><%= link_to "Ingresar", new_user_session_path %></li>
          <li><%= link_to "Registrarse", new_user_registration_path %></li>
          <%= render 'layouts/search' %>
        <% else %>
          <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
          <%= render 'layouts/search' %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_search.html.erb
<!-- Este form no tiene Submit Button porque al ser un text_field con presionar ENTER envía los datos -->

<%= form_tag questions_path, method: :get, class:"navbar-form navbar-left" do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class:"form-control", placeholder:"Buscar pregunta" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProyectoStackoverflow" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>